### ISSUE TITLE
1.2.0 did not fix loading error

### ISSUE THREAD

**Issue by spyjoshx** [embeddedt/CreateChunkloading#8]
```---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 7/12/22, 11:08 AM
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:55) ~[forge-1.18.2-40.1.52-universal.jar%2396!/:?] {re:classloading}
	at net.minecraftforge.client.loading.ClientModLoader.completeModLoading(ClientModLoader.java:170) ~[forge-1.18.2-40.1.52-universal.jar%2396!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$new$1(Minecraft.java:555) ~[client-1.18.2-20220404.173914-srg.jar%2391!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.Util.m_137521_(Util.java:397) ~[client-1.18.2-20220404.173914-srg.jar%2391!/:?] {re:classloading}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:549) ~[client-1.18.2-20220404.173914-srg.jar%2391!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.LoadingOverlay.m_6305_(LoadingOverlay.java:135) ~[client-1.18.2-20220404.173914-srg.jar%2391!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:879) ~[client-1.18.2-20220404.173914-srg.jar%2391!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1044) ~[client-1.18.2-20220404.173914-srg.jar%2391!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:663) ~[client-1.18.2-20220404.173914-srg.jar%2391!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%2391!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.1.52.jar%2350!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:57) [ForgeWrapper-mmc2.jar:mmc2] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at org.multimc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104) [NewLaunch.jar:?] {}
	at org.multimc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175) [NewLaunch.jar:?] {}
	at org.multimc.impl.OneSixLauncher.launch(OneSixLauncher.java:185) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.listen(EntryPoint.java:127) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.main(EntryPoint.java:57) [NewLaunch.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at org.embeddedt.createchunkloading.CreateChunkloading.init(CreateChunkloading.java:34) ~[createchunkloading-1.1.0-forge.jar%2363!/:?] {re:classloading}
-- MOD createchunkloading --
Details:
	Caused by 0: java.lang.reflect.InvocationTargetException
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
		at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:67) ~[javafmllanguage-1.18.2-40.1.52.jar%2393!/:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:106) ~[fmlcore-1.18.2-40.1.52.jar%2392!/:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

	Mod File: createchunkloading-1.2.0-forge.jar
	Failure message: Create Chunkloading (createchunkloading) has failed to load correctly
		java.lang.reflect.InvocationTargetException: null
	Mod Version: 1.2.0
	Mod Issue URL: NOT PROVIDED
	Exception message: java.lang.NoSuchMethodError: 'void com.simibubi.create.AllMovementBehaviours.addMovementBehaviour(net.minecraft.resources.ResourceLocation, com.simibubi.create.content.contraptions.components.structureMovement.MovementBehaviour)'
Stacktrace:
	at org.embeddedt.createchunkloading.CreateChunkloading.init(CreateChunkloading.java:34) ~[createchunkloading-1.1.0-forge.jar%2363!/:?] {re:classloading}
	at org.embeddedt.createchunkloading.forge.CreateChunkloadingForge.<init>(CreateChunkloadingForge.java:17) ~[createchunkloading-1.1.0-forge.jar%2363!/:?] {re:classloading}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:67) ~[javafmllanguage-1.18.2-40.1.52.jar%2393!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:106) ~[fmlcore-1.18.2-40.1.52.jar%2392!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}


-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Linux (amd64) version 5.18.9-200.fc36.x86_64
	Java Version: 17.0.1, Flathub
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Flathub
	Memory: 1411090920 bytes (1345 MiB) / 2420113408 bytes (2308 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-10700KF CPU @ 3.80GHz
	Identifier: Intel64 Family 6 Model 165 Stepping 5
	Microarchitecture: unknown
	Frequency (GHz): 3.80
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: Device
	Graphics card #0 vendor: NVIDIA Corporation (0x10de)
	Graphics card #0 VRAM (MB): 288.00
	Graphics card #0 deviceId: 0x2206
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 16043.04
	Virtual memory used (MB): 7826.81
	Swap memory total (MB): 8192.00
	Swap memory used (MB): 0.00
	JVM Flags: 2 total; -Xms512m -Xmx4096m
	ModLauncher: 9.1.3+9.1.3+main.9b69c82a
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 slf4jfixer PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		client-1.18.2-20220404.173914-srg.jar             |Minecraft                     |minecraft                     |1.18.2              |COMMON_SET|Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		TConstruct-1.18.2-3.5.1.31.jar                    |Tinkers' Construct            |tconstruct                    |3.5.1.31            |COMMON_SET|Manifest: NOSIGNATURE
		create-stuff-additions1.18.2_v1.1.7.jar           |Create Stuff Additions        |create_stuff_additions        |1.1.7               |COMMON_SET|Manifest: NOSIGNATURE
		voicechat-forge-1.18.2-2.2.50.jar                 |Simple Voice Chat             |voicechat                     |1.18.2-2.2.50       |COMMON_SET|Manifest: NOSIGNATURE
		AmbientSounds_FORGE_v5.0.16_mc1.18.2.jar          |Ambient Sounds                |ambientsounds                 |5.0.16              |COMMON_SET|Manifest: NOSIGNATURE
		CreativeCore_FORGE_v2.6.12_mc1.18.2.jar           |CreativeCore                  |creativecore                  |2.6.12              |COMMON_SET|Manifest: NOSIGNATURE
		jei-1.18.2-9.7.0.209.jar                          |Just Enough Items             |jei                           |9.7.0.209           |COMMON_SET|Manifest: NOSIGNATURE
		Map Atlases-forge-1.18.2-2.1.0.jar                |Map Atlases                   |map_atlases                   |2.1.0               |COMMON_SET|Manifest: NOSIGNATURE
		pamhc2foodextended-1.18.2-1.0.0.jar               |Pam's HarvestCraft 2 - Food Ex|pamhc2foodextended            |1.0                 |COMMON_SET|Manifest: NOSIGNATURE
		flywheel-forge-1.18-0.6.4.jar                     |Flywheel                      |flywheel                      |1.18-0.6.4.87       |COMMON_SET|Manifest: NOSIGNATURE
		curios-forge-1.18.2-5.0.7.1.jar                   |Curios API                    |curios                        |1.18.2-5.0.7.1      |COMMON_SET|Manifest: NOSIGNATURE
		Mantle-1.18.2-1.9.27.jar                          |Mantle                        |mantle                        |1.9.27              |COMMON_SET|Manifest: NOSIGNATURE
		create-mc1.18.2_v0.5.0b.jar                       |Create                        |create                        |0.5.0b              |COMMON_SET|Manifest: NOSIGNATURE
		Xaeros_Minimap_22.11.1_Forge_1.18.2.jar           |Xaero's Minimap               |xaerominimap                  |22.11.1             |COMMON_SET|Manifest: NOSIGNATURE
		waystones-forge-1.18.2-10.1.0.jar                 |Waystones                     |waystones                     |10.1.0              |COMMON_SET|Manifest: NOSIGNATURE
		pamhc2foodcore-1.18.2-1.0.1.jar                   |Pam's HarvestCraft 2 - Food Co|pamhc2foodcore                |1.0.1               |COMMON_SET|Manifest: NOSIGNATURE
		baubley-heart-canisters-1.18.2-1.0.0.jar          |Baubley Heart Canisters       |bhc                           |1.18.2-1.0.0        |COMMON_SET|Manifest: NOSIGNATURE
		XaerosWorldMap_1.25.1_Forge_1.18.2.jar            |Xaero's World Map             |xaeroworldmap                 |1.25.1              |COMMON_SET|Manifest: NOSIGNATURE
		cookingforblockheads-forge-1.18.2-12.0.2.jar      |CookingForBlockheads          |cookingforblockheads          |12.0.2              |COMMON_SET|Manifest: NOSIGNATURE
		AutoRegLib-1.7-53.jar                             |AutoRegLib                    |autoreglib                    |1.7-53              |COMMON_SET|Manifest: NOSIGNATURE
		mna-1.7.2.5.jar                                   |Mana and Artifice             |mna                           |1.7.2.5             |COMMON_SET|Manifest: NOSIGNATURE
		CustomPlayerModels-1.18-0.4.3a.jar                |Customizable Player Models    |cpm                           |0.4.3a              |COMMON_SET|Manifest: NOSIGNATURE
		xercapaint-1.18.2-0.7.1.jar                       |Joy of Painting               |xercapaint                    |1.18.2-0.7.1        |COMMON_SET|Manifest: NOSIGNATURE
		architectury-4.5.76-forge.jar                     |Architectury                  |architectury                  |4.5.76              |COMMON_SET|Manifest: NOSIGNATURE
		createchunkloading-1.2.0-forge.jar                |Create Chunkloading           |createchunkloading            |1.2.0               |ERROR     |Manifest: NOSIGNATURE
		cc-tweaked-1.18.2-1.100.8.jar                     |CC: Tweaked                   |computercraft                 |1.100.8             |COMMON_SET|Manifest: NOSIGNATURE
		mahoutsukai-1.18.2-v1.34.27.jar                   |Mahou Tsukai                  |mahoutsukai                   |1.18.2-v1.34.27     |COMMON_SET|Manifest: NOSIGNATURE
		balm-3.1.0+0.jar                                  |Balm                          |balm                          |3.1.0+0             |COMMON_SET|Manifest: NOSIGNATURE
		JustEnoughResources-1.18.2-0.14.1.171.jar         |Just Enough Resources         |jeresources                   |0.14.1.171          |COMMON_SET|Manifest: NOSIGNATURE
		forge-1.18.2-40.1.52-universal.jar                |Forge                         |forge                         |40.1.52             |COMMON_SET|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		Quark-3.2-358.jar                                 |Quark                         |quark                         |3.2-358             |COMMON_SET|Manifest: NOSIGNATURE
		cofh_core-1.18.2-1.6.4.21.jar                     |CoFH Core                     |cofh_core                     |1.6.4.21            |COMMON_SET|Manifest: 75:0b:cc:9b:64:2e:9b:c4:41:d1:95:00:71:ee:87:1a:b3:5e:4b:da:8e:e8:39:00:fd:5d:e5:9c:40:42:33:09
		thermal_foundation-1.18.2-1.6.3.28.jar            |Thermal Series                |thermal                       |1.6.3.28            |COMMON_SET|Manifest: 75:0b:cc:9b:64:2e:9b:c4:41:d1:95:00:71:ee:87:1a:b3:5e:4b:da:8e:e8:39:00:fd:5d:e5:9c:40:42:33:09
		thermal_innovation-1.18.2-1.6.3.12.jar            |Thermal Innovation            |thermal_innovation            |1.6.3.12            |COMMON_SET|Manifest: 75:0b:cc:9b:64:2e:9b:c4:41:d1:95:00:71:ee:87:1a:b3:5e:4b:da:8e:e8:39:00:fd:5d:e5:9c:40:42:33:09
		thermal_expansion-1.18.2-1.6.3.13.jar             |Thermal Expansion             |thermal_expansion             |1.6.3.13            |COMMON_SET|Manifest: 75:0b:cc:9b:64:2e:9b:c4:41:d1:95:00:71:ee:87:1a:b3:5e:4b:da:8e:e8:39:00:fd:5d:e5:9c:40:42:33:09
		xercamusic-1.18.2-1.0.0.jar                       |Xerca's Music Maker Mod       |xercamusic                    |1.18.2-1.0.0        |COMMON_SET|Manifest: NOSIGNATURE
		geckolib-forge-1.18-3.0.28.jar                    |GeckoLib                      |geckolib3                     |3.0.28              |COMMON_SET|Manifest: NOSIGNATURE
		selene-1.18.2-1.17.9.jar                          |Selene                        |selene                        |1.18.2-1.17.9       |COMMON_SET|Manifest: NOSIGNATURE
		supplementaries-1.18.2-1.4.8.jar                  |Supplementaries               |supplementaries               |1.18.2-1.4.8        |COMMON_SET|Manifest: NOSIGNATURE
		createaddition-1.18.2-20220712a.jar               |Create Crafts & Additions     |createaddition                |1.18.2-20220712a    |COMMON_SET|Manifest: NOSIGNATURE
	Flywheel Backend: GL33 Instanced Arrays
	Crash Report UUID: 8857a206-b5bf-4d79-bdd4-6ad1c8a66081
	FML: 40.1
	Forge: net.minecraftforge:40.1.52
```

This is the same error that I got with 1.1.0. All mods are at their latest versions from Curseforge.

**Comment by embeddedt** [comment]
I'm not able to reproduce this. I created a fresh Forge 40.1.52 instance and downloaded Create 0.5.0b, Flywheel 0.6.4, Architectury 4.5.76, and Create Chunkloading 1.2.0, all directly from CurseForge. The game launches without issues for me.

Can you try creating a fresh instance to make sure this is not an issue specific to your pack?

**Comment by spyjoshx** [comment]
When I was copying the mods over to my new instance to test, I found that the old create-chunkloading was still there alongside 1.2.0. I guess packwiz forgot to delete the old one. It works fine now thank you.
